### ISSUE TITLE
Instance Queries are not supported.

### ISSUE THREAD

**Issue by VivaRado** [VivaRado/SYFF#1]
We can parse but we do not recurse instance queries yet. For example here is an instance query for the bold weight.

```css
@instance (bold) { 

	A [ B = "name, unicode" ] {

		partial: keep("partial_a", "partial_b");
		partial: remove("partial_b");
		partial: get("Π","partial_a","partial_a_rename");
		partial: copy("partial_a", "partial_b");

	}

}

```
